version: 3.0.3.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "3.0.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "3.0.3-CI-{build}"

configuration: Release

before_build: nuget restore

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/
  api_key:
    secure: rCUEY75fXN0wxtMy6QL4jCrLdaYbxIBzIXWeN+wEu/XDpyqimzreOc5AH5jMd5ah
  symbol_server: https://nuget.symbolsource.org/MyGet/autofac
