<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Autofac extension supporting generation of FakeItEasy objects.</Description>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>Autofac.Extras.FakeItEasy</AssemblyName>
    <AssemblyOriginatorKeyFile>../../Autofac.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <PackageId>Autofac.Extras.FakeItEasy</PackageId>
    <PackageTags>autofac;di;ioc;dependencyinjection;mocks;mocking;fakes;stubs;doubles;substitutes</PackageTags>
    <PackageReleaseNotes>Release notes are at https://github.com/autofac/Autofac.Extras.FakeItEasy/releases</PackageReleaseNotes>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://autofac.org</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/autofac/Autofac.Extras.FakeItEasy</RepositoryUrl>
    <AssemblyTitle>Autofac.Extras.FakeItEasy</AssemblyTitle>
    <NeutralLanguage>en</NeutralLanguage>
    <Copyright>Copyright © 2014 Autofac Contributors</Copyright>
    <CodeAnalysisRuleSet>../../build/Source.ruleset</CodeAnalysisRuleSet>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedAllSources>true</EmbedAllSources>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <Features>IOperation</Features>
    <Authors>Autofac Contributors</Authors>
    <Company>Autofac</Company>
    <Product>Autofac</Product>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\build\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\..\build\stylecop.json" Link="stylecop.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.1.0" />
    <PackageReference Include="FakeItEasy" Version="9.0.1" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300" Condition="Exists('$(MSBuildThisFileDirectory)../../.git')">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
