<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Assembly metadata -->
    <AssemblyName>Autofac.Extras.FakeItEasy</AssemblyName>
    <AssemblyTitle>Autofac.Extras.FakeItEasy</AssemblyTitle>
    <Description>Autofac extension supporting generation of FakeItEasy objects.</Description>
    <Copyright>Copyright © 2014 Autofac Contributors</Copyright>
    <Authors>Autofac Contributors</Authors>
    <Company>Autofac</Company>
    <Product>Autofac</Product>
    <AssemblyOriginatorKeyFile>../../Autofac.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <NeutralLanguage>en-US</NeutralLanguage>
    <!-- Frameworks and language features -->
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <CodeAnalysisRuleSet>../../build/Source.ruleset</CodeAnalysisRuleSet>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- Packaging -->
    <PackageId>Autofac.Extras.FakeItEasy</PackageId>
    <PackageTags>autofac;di;ioc;dependencyinjection;mocks;mocking;fakes;stubs;doubles;substitutes</PackageTags>
    <PackageReleaseNotes>Release notes are at https://github.com/autofac/Autofac.Extras.FakeItEasy/releases</PackageReleaseNotes>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://autofac.org</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/autofac/Autofac.Extras.FakeItEasy</RepositoryUrl>
    <ContinuousIntegrationBuild Condition="'$(CI)' != '' ">true</ContinuousIntegrationBuild>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedAllSources>true</EmbedAllSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <!-- OmniSharp/VS Code resource generation -->
    <CoreCompileDependsOn>PrepareResources;$(CompileDependsOn)</CoreCompileDependsOn>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\build\icon.png" Pack="true" PackagePath="\" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="../../build/stylecop.json" Link="stylecop.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.3.1" />
    <PackageReference Include="FakeItEasy" Version="9.0.1" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300" Condition="Exists('$(MSBuildThisFileDirectory)../../.git')">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.28.0.143324">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
